# Generated by Django 4.2.7 on 2023-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromValue', models.FloatField()),
                ('toValue', models.FloatField()),
            ],
        ),
    ]
