# Generated by Django 4.2.7 on 2023-11-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_date_alter_todo_status_alter_todo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='addDate',
        ),
        migrations.AddField(
            model_name='todo',
            name='dueDate',
            field=models.DateField(null=True),
        ),
    ]
