# Generated by Django 4.2.7 on 2023-11-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_date_todo_adddate_todo_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='addDate',
            field=models.DateTimeField(null=True),
        ),
    ]
